In [48]:
import pandas as pd
import numpy as np
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
RANDOM_TENSOR = torch.rand(3,4)
RANDOM_TENSOR

tensor([[0.4988, 0.4160, 0.3187, 0.6212],
        [0.8023, 0.8668, 0.0907, 0.5666],
        [0.1079, 0.2966, 0.7508, 0.9573]])

In [7]:
ZEROS = torch.zeros(4,5)
ZEROS

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
ZEROS_LIKE = torch.zeros_like(RANDOM_TENSOR)
ZEROS_LIKE

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
RANGE = torch.arange(3,10)
RANGE

tensor([3, 4, 5, 6, 7, 8, 9])

In [6]:
class InvalidMatrixShape(Exception):
    pass

def matrix_mul(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor:
    if (A.shape[1] != B.shape[0]):
        raise InvalidMatrixShape()
    n,m = A.shape[0], B.shape[1]
    C = torch.zeros(n,m)
    B_T = B.T
    for i in range(n):
        for j in range(m):
            C[i][j] = torch.dot(A[i] , B_T[j])
    return C



In [27]:
A = torch.tensor([
    [6,3,5],
    [2,4,1]
])

B = torch.tensor([
    [1,4],
    [2,5],
    [3,6]
])

In [8]:
%%time

A @ B

CPU times: user 10.2 ms, sys: 563 μs, total: 10.8 ms
Wall time: 8.97 ms


tensor([[22, 49],
        [28, 64]])

In [9]:
%%time
matrix_mul(A,B)

CPU times: user 10.4 ms, sys: 596 μs, total: 11 ms
Wall time: 9.97 ms


tensor([[22., 49.],
        [28., 64.]])

In [13]:
X = torch.arange(0,100)

In [23]:
X.type(torch.float).mean()

tensor(49.5000)

In [49]:
torch.cuda.is_available()

True

In [50]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [52]:
X.to(device)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99], device='cuda:0')

Fri Sep 11 00:22:11 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.16              Driver Version: 572.16         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              5W /   95W |      81MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----